import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import type { JsonMap } from '../types';
import { Badge, Card, Field, Loading, Modal, PageTitle, Stat, Table, fmtDate } from '../components/ui';

export default function AdminDashboard(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''); const [overview,setOverview]=useState<JsonMap>({}),[departments,setDepartments]=useState<JsonMap[]>([]),[incidents,setIncidents]=useState<JsonMap[]>([]),[findings,setFindings]=useState<JsonMap[]>([]),[clinical,setClinical]=useState<JsonMap[]>([]),[staff,setStaff]=useState<JsonMap[]>([]),[actions,setActions]=useState<JsonMap[]>([]),[ann,setAnn]=useState<JsonMap[]>([]); const [mode,setMode]=useState<'action'|'announcement'|null>(null); const [form,setForm]=useState({title:'',details:'',priority:'normal',department_id:''});
 async function load(){setLoading(true);setError('');try{const c=await Promise.all(['provider_admin_overview','provider_admin_departments','provider_admin_incidents','provider_admin_findings','provider_admin_clinical_workload','provider_admin_staff_summary','provider_admin_management_actions','provider_admin_announcements'].map(fn=>supabase.rpc(fn)));const bad=c.find(x=>x.error);if(bad?.error)throw bad.error;setOverview(c[0].data??{});setDepartments(c[1].data??[]);setIncidents(c[2].data??[]);setFindings(c[3].data??[]);setClinical(c[4].data??[]);setStaff(c[5].data??[]);setActions(c[6].data??[]);setAnn(c[7].data??[])}catch(e:any){setError(e.message||String(e))}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();const req=mode==='action'?supabase.rpc('provider_admin_create_management_action',{p_title:form.title,p_details:form.details,p_priority:form.priority,p_department_id:form.department_id||null}):supabase.rpc('provider_admin_create_announcement',{p_title:form.title,p_body:form.details,p_department_id:form.department_id||null});const {error}=await req;if(error)setError(error.message);else{setMode(null);setForm({title:'',details:'',priority:'normal',department_id:''});load()}}
 async function update(id:string,status:string){const {error}=await supabase.rpc('provider_admin_update_management_action',{p_action_id:id,p_status:status});if(error)setError(error.message);else load()}
 if(loading)return <Loading/>; const stats=Object.entries(overview);
 return <><PageTitle title="Hospital Admin / General Manager" subtitle="Hospital-wide daily operations and management." actions={<><button className="btn btn-secondary" onClick={()=>setMode('announcement')}>Announcement</button><button className="btn btn-primary" onClick={()=>setMode('action')}>Management action</button></>}/>{error&&<div className="error">{error}</div>}<div className="stats-grid">{stats.map(([k,v])=><Stat key={k} label={k.replaceAll('_',' ')} value={String(v??0)}/>)}</div>
 <div className="grid-2"><Card title="Departments"><Table rows={departments} columns={[{key:'name',label:'Department'},{key:'staff_count',label:'Staff'},{key:'open_tasks',label:'Tasks'},{key:'open_incidents',label:'Incidents'}]}/></Card><Card title="Clinical workload"><Table rows={clinical} columns={[{key:'work_type',label:'Area'},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'item_count',label:'Items'}]}/></Card></div>
 <Card title="Management actions"><Table rows={actions} columns={[{key:'title',label:'Action'},{key:'department_name',label:'Department'},{key:'priority',label:'Priority',render:r=><Badge value={r.priority}/>},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'created_at',label:'Created',render:r=>fmtDate(r.created_at)},{key:'change',label:'Change',render:r=><select value={r.status} onChange={e=>update(String(r.id),e.target.value)}><option>open</option><option>in_progress</option><option>resolved</option><option>closed</option></select>}]} /></Card>
 <div className="grid-2"><Card title="Open incidents"><Table rows={incidents} columns={[{key:'title',label:'Incident'},{key:'department_name',label:'Department'},{key:'severity',label:'Severity',render:r=><Badge value={r.severity}/>},{key:'status',label:'Status',render:r=><Badge value={r.status}/>}]} /></Card><Card title="Compliance findings"><Table rows={findings} columns={[{key:'title',label:'Finding'},{key:'department_name',label:'Department'},{key:'severity',label:'Severity',render:r=><Badge value={r.severity}/>},{key:'status',label:'Status',render:r=><Badge value={r.status}/>}]} /></Card></div>
 <div className="grid-2"><Card title="Staff summary"><Table rows={staff} columns={[{key:'role_label',label:'Role'},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'staff_count',label:'Count'}]}/></Card><Card title="Announcements"><Table rows={ann} columns={[{key:'title',label:'Title'},{key:'department_name',label:'Department'},{key:'created_at',label:'Created',render:r=>fmtDate(r.created_at)}]}/></Card></div>
 {mode&&<Modal title={mode==='action'?'Create management action':'Create announcement'} onClose={()=>setMode(null)}><form className="form-grid" onSubmit={submit}><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Department"><select value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Hospital-wide</option>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></Field>{mode==='action'&&<Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>normal</option><option>high</option><option>critical</option></select></Field>}<Field label={mode==='action'?'Details':'Message'}><textarea required rows={5} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></Field><div className="form-actions"><button className="btn btn-secondary" type="button" onClick={()=>setMode(null)}>Cancel</button><button className="btn btn-primary">Save</button></div></form></Modal>}
 </>;
}
