import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import type { JsonMap } from '../types';
import { Badge, Card, Field, Loading, Modal, PageTitle, Stat, Table, fmtDate } from '../components/ui';

export default function OwnerDashboard(){
  const [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [overview,setOverview]=useState<JsonMap>({}), [leadership,setLeadership]=useState<JsonMap[]>([]), [branches,setBranches]=useState<JsonMap[]>([]), [departments,setDepartments]=useState<JsonMap[]>([]), [risks,setRisks]=useState<JsonMap[]>([]), [directives,setDirectives]=useState<JsonMap[]>([]), [audit,setAudit]=useState<JsonMap[]>([]);
  const [show,setShow]=useState(false); const [form,setForm]=useState({title:'',details:'',priority:'normal',department_id:''});
  async function load(){setLoading(true);setError('');try{const calls=await Promise.all([
    supabase.rpc('provider_owner_overview'),supabase.rpc('provider_owner_leadership'),supabase.rpc('provider_owner_branches'),supabase.rpc('provider_owner_departments'),supabase.rpc('provider_owner_risks'),supabase.rpc('provider_owner_directives'),supabase.rpc('provider_owner_recent_audit')]);
    const bad=calls.find(x=>x.error); if(bad?.error) throw bad.error;
    setOverview(calls[0].data??{}); setLeadership(calls[1].data??[]); setBranches(calls[2].data??[]); setDepartments(calls[3].data??[]); setRisks(calls[4].data??[]); setDirectives(calls[5].data??[]); setAudit(calls[6].data??[]);
  }catch(e:any){setError(e.message||String(e))}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function create(e:FormEvent){e.preventDefault();const {error}=await supabase.rpc('provider_owner_create_directive',{p_title:form.title,p_details:form.details,p_priority:form.priority,p_department_id:form.department_id||null});if(error){setError(error.message);return}setShow(false);setForm({title:'',details:'',priority:'normal',department_id:''});load()}
  async function update(id:string,status:string){const {error}=await supabase.rpc('provider_owner_update_directive',{p_directive_id:id,p_status:status});if(error)setError(error.message);else load()}
  if(loading) return <Loading/>;
  return <><PageTitle title="Owner / Super Admin" subtitle="Executive control center for the entire hospital organization." actions={<button className="btn btn-primary" onClick={()=>setShow(true)}>New directive</button>}/>{error&&<div className="error">{error}</div>}
  <div className="stats-grid"><Stat label="Approved staff" value={overview.approved_staff}/><Stat label="Admins / GM" value={overview.admins}/><Stat label="Department managers" value={overview.department_managers}/><Stat label="Active branches" value={overview.active_branches}/><Stat label="Departments" value={overview.departments}/><Stat label="Today's appointments" value={overview.today_appointments}/><Stat label="Critical risks" value={overview.critical_risks}/><Stat label="Open directives" value={overview.open_directives}/></div>
  <div className="grid-2"><Card title="Leadership"><Table rows={leadership} columns={[{key:'full_name',label:'Name'},{key:'role_label',label:'Role'},{key:'department_name',label:'Department'},{key:'status',label:'Status',render:r=><Badge value={r.status}/>}]} /></Card><Card title="High / critical risks"><Table rows={risks} columns={[{key:'source_type',label:'Source'},{key:'title',label:'Issue'},{key:'department_name',label:'Department'},{key:'severity',label:'Severity',render:r=><Badge value={r.severity}/>},{key:'status',label:'Status',render:r=><Badge value={r.status}/>}]} /></Card></div>
  <Card title="Owner directives"><Table rows={directives} columns={[{key:'title',label:'Directive'},{key:'department_name',label:'Department'},{key:'priority',label:'Priority',render:r=><Badge value={r.priority}/>},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'created_at',label:'Created',render:r=>fmtDate(r.created_at)},{key:'actions',label:'Action',render:r=><select value={r.status} onChange={e=>update(String(r.id),e.target.value)}><option>open</option><option>in_progress</option><option>resolved</option><option>closed</option></select>}]} /></Card>
  <div className="grid-2"><Card title="Branches"><Table rows={branches} columns={[{key:'name',label:'Branch'},{key:'city',label:'City'},{key:'staff_count',label:'Staff'},{key:'is_active',label:'Active',render:r=><Badge value={r.is_active?'active':'inactive'}/>}]}/></Card><Card title="Departments"><Table rows={departments} columns={[{key:'name',label:'Department'},{key:'staff_count',label:'Staff'},{key:'manager_count',label:'Managers'},{key:'open_tasks',label:'Open tasks'},{key:'open_incidents',label:'Incidents'}]}/></Card></div>
  <Card title="Recent audit activity"><Table rows={audit} columns={[{key:'action',label:'Action'},{key:'entity_type',label:'Entity'},{key:'actor_name',label:'Actor'},{key:'created_at',label:'When',render:r=>fmtDate(r.created_at)}]}/></Card>
  {show&&<Modal title="Create owner directive" onClose={()=>setShow(false)}><form className="form-grid" onSubmit={create}><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Department"><select value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Hospital-wide</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>normal</option><option>high</option><option>critical</option></select></Field><Field label="Details"><textarea required rows={5} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></Field><div className="form-actions"><button className="btn btn-secondary" type="button" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary">Create directive</button></div></form></Modal>}
  </>;
}
